# NO TE QUEDES SIN TU LAPTOP!!

***

#### - Prueva tu suerte, obten una cantidad de puntos y GANA!!

#### PREMIOS:

#### CON 1200 Puntos
* Una Laptop ASUS GA401II-HE003T 14" IPS FHD, AMD Ryzen 7 4800HS 2.9 / 4.20 GHz, 16GB DDR4, 512GB SSD, Nvidia GeForce GTX 1650Ti 4GB. Windows 10 Home

![imagen](https://www.buyima.com/455-medium_default/notebook-asus-ga401ii-he003t-14-ips-fhd-amd-ryzen-7-4800hs-29-420-ghz-16gb-ddr4.jpg)

#### Con 900 Puntos
* Una LAPTOP HP PAVILION GAMING 16-A0001LA INTEL CORE I5 8GB 512GB SSD 4GB

![imagen](https://plazavea.vteximg.com.br/arquivos/ids/2026717-450-450/20199935.jpg)

### Con 600 puntos
* Una Laptop Lenovo IdeaPad 3 14IIL05 14" Intel Core i3 1005G1 1TB 4GB RAM

![imagen](https://hiraoka.com.pe/media/catalog/product/cache/a357cb11a228eb6f7f15c0ee1ff203af/1/2/122077_1_1.jpg)

### Con 300 puntos
* Una Laptop HP Pavilion dv4-1413LA con procesador AMD Athlon X2 QL-65,3 GB DDR2 de ram, pantalla LED 14.1" (1280x800)

![imagen](https://m.media-amazon.com/images/I/41SQNBvVs4L._AC_SY355_.jpg)

### Con 100 puntos
* Una laptop eleron N4000 con 2 de ram y una pantalla 4k de 60hz.

![imagen](http://www.joelsedano.com/blog/wp-content/uploads/2017/02/gpd-win.jpg)

In [12]:
import numpy as np
a = numpy.array([1,100,200])
print(a)

[  1 100 200]


In [13]:
newArray = numpy.append(a, [300,900,1200])
print(newArray)

[   1  100  200  300  900 1200]


In [15]:
m = np.random.rand(1200)
print(m)

[0.82433062 0.91049169 0.10965154 ... 0.71021304 0.52402812 0.97767461]


***

### Prueba tu suerte!!!

In [24]:
#Prueba tu suerte!!!
m = np.random.randint(1200)
print(m)

1133


In [26]:
cantidad = 1133
if cantidad >=1200:
    print("Felicidades ganaste el premio MAYOR!!")
elif cantidad >=900:
    print("Canjeable una LAPTOP HP PAVILION GAMING!! ")
elif cantidad >=600:
    print("Canjeable por una Laptop Lenovo IdeaPad 3")
elif cantidad >=300:
    print("Canjeable por una Laptop HP Pavilion")
elif cantidad >=100:
    print("Canjeable por una laptop eleron N4000")
elif cantidad <=99:
    print("Lo siento..., Suerte para la proxima")

Canjeable una LAPTOP HP PAVILION GAMING!! 
